services:
  - type: web
    name: paddy-rice-tracker
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn "website:create_app()"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: paddy-rice-tracker-db
          property: connectionString
      - key: SECRET_KEY
        value: your-super-secret-key
